source("steel.R")

# csv file should be generated by the format of save_txt_for_R_statistical_test in misc/plotter/return_plotter.py
x <- read.table("/home/karino/master/matlab_utils/multicomp_utils/sac_test.csv", header=T, sep=",")

# xのキーStepがstep100000かつxのキーMethodがDefaultのデータを抽出
d1d = x[x$Step=="step1000000" & x$Method=="Default", "y"]
d2d = x[x$Step=="step2000000" & x$Method=="Default", "y"]
e1d = x[x$Step=="step1000000" & x$Method=="EExploitation", "y"]
e2d = x[x$Step=="step2000000" & x$Method=="EExploitation", "y"]
l1d = x[x$Step=="step1000000" & x$Method=="large_variance", "y"]
l2d = x[x$Step=="step2000000" & x$Method=="large_variance", "y"]

# the first one is control (l1d, l2d)
test1 <- c(l1d, d1d, e1d)
test2 <- c(l2d, d2d, e2d)

df1 <- data.frame(response = test1, group = rep(letters[1:3], each = 25))
df2 <- data.frame(response = test2, group = rep(letters[1:3], each = 25))
print("both sided test")
r1 <- steel.test(response ~ group, data = df1, control = "a")
r2 <- steel.test(response ~ group, data = df2, control = "a")
print(r1)
print(r2)
# print("one sided test")
# r <- steel.test(response ~ group, data = df2, control = "a", alternative = "less")
# print(r)
